examples/RapidField.SolidInstruments.Prototype.WebApplication/Models/FibonacciSequence/IndexModel.cs
// =================================================================================================================================
// Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
// =================================================================================================================================

using System;
using System.Collections.Generic;

namespace RapidField.SolidInstruments.Example.WebApplication.Models.FibonacciSequence
{
    /// <summary>
    /// Represents a view model for the path ~/FibonacciSequence
    /// </summary>
    public class IndexModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexModel" /> class.
        /// </summary>
        public IndexModel()
            : this(null)
        {
            return;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IndexModel" /> class.
        /// </summary>
        /// <param name="terms">
        /// A collection of Fibonacci sequence terms.
        /// </param>
        public IndexModel(ICollection<Int64> terms)
        {
            Terms = terms;
        }

        /// <summary>
        /// Gets or sets a collection of Fibonacci sequence terms.
        /// </summary>
        public ICollection<Int64> Terms
        {
            get;
            set;
        }
    }
}

examples/RapidField.SolidInstruments.Prototype.WebApplication/Controllers/FibonacciSequenceController.cs
// =================================================================================================================================
// Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
// =================================================================================================================================

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RapidField.SolidInstruments.Command;
using RapidField.SolidInstruments.Example.DatabaseModel;
using RapidField.SolidInstruments.Example.WebApplication.Models.FibonacciSequence;
using RapidField.SolidInstruments.Mathematics.Sequences;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RapidField.SolidInstruments.Example.WebApplication.Controllers
{
    /// <summary>
    /// Processes requests for the path ~/FibonacciSequence
    /// </summary>
    public sealed class FibonacciSequenceController : ApplicationController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FibonacciSequenceController" /> class.
        /// </summary>
        /// <param name="applicationConfiguration">
        /// Configuration information for the application.
        /// </param>
        /// <param name="mediator">
        /// A processing intermediary for commands issued by the controller.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// <paramref name="applicationConfiguration" /> is <see langword="null" /> -or- <paramref name="mediator" /> is
        /// <see langword="null" />.
        /// </exception>
        public FibonacciSequenceController(IConfiguration applicationConfiguration, ICommandMediator mediator)
            : base(applicationConfiguration, mediator)
        {
            return;
        }

        /// <summary>
        /// Processes GET requests for the path ~/FibonacciSequence
        /// </summary>
        /// <returns>
        /// A <see cref="ViewResult" />.
        /// </returns>
        [HttpGet]
        public IActionResult Index()
        {
            var fibonacciNumberValues = new List<Int64>(Mediator.Process(ExampleCommands.GetFibonacciNumberValues()));
            var fibonacciSequence = FibonacciSequence.Classic;

            if (fibonacciNumberValues.Any())
            {
                while (true)
                {
                    var value = (Int64)fibonacciSequence.CalculateNext();

                    if (fibonacciNumberValues.Contains(value))
                    {
                        continue;
                    }

                    fibonacciNumberValues.Add(value);
                    Mediator.Process(ExampleCommands.AddFibonacciNumber(value));
                    break;
                }
            }
            else
            {
                var initialTerms = fibonacciSequence.ToArray(0, fibonacciSequence.CalculatedTermCount);

                foreach (var term in initialTerms)
                {
                    var value = (Int64)term;
                    fibonacciNumberValues.Add(value);
                    Mediator.Process(ExampleCommands.AddFibonacciNumber(value));
                }
            }

            var model = new IndexModel(fibonacciNumberValues);
            return View(model);
        }
    }
}

examples/RapidField.SolidInstruments.Prototype.WebApplication/Views/FibonacciSequence/Index.cshtml
@*
    Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
*@

@using RapidField.SolidInstruments.Example.WebApplication.Models.FibonacciSequence
@model IndexModel
@{
    ViewData["Title"] = "Fibonacci sequence generator";
}

<div class="col-lg-12">
    <h1>
        Fibonacci sequence generator
    </h1>
    <h4 class="margin-vertical-md">
        This demo uses an in-memory database to persist calculated Fibonacci numbers.
    </h4>
    <hr />
    <p>
        <span class="glyphicon glyphicon-info-sign"></span> <strong>Types employed by this demonstration:</strong>
    </p>
    <ul class="list-inline list-group">
        <li class="list-group-item-info margin-all-xs padding-all-sm">InversionOfControl.DotNetNative.<strong>DotNetNativeDependencyModule</strong></li>
        <li class="list-group-item-info margin-all-xs padding-all-sm">DataAccess.EntityFramework.<strong>ConfiguredContext</strong></li>
        <li class="list-group-item-info margin-all-xs padding-all-sm">Mathematics.Sequences.<strong>FibonacciSequence</strong></li>
    </ul>
    <hr />
    <div class="center-block text-center">
    </div>
    <ul class="list-inline list-group">
        @foreach (var term in Model.Terms)
        {
            <li class="list-group-item margin-all-sm padding-horizontal-md">
                @term.ToString("n0")
            </li>
        }
        <li class="list-group-item margin-all-sm padding-horizontal-md">
            <span class="glyphicon glyphicon-chevron-right"></span>
            @Html.ActionLink("Generate next term", "Index", "FibonacciSequence")
            <span class="glyphicon glyphicon-chevron-left"></span>
        </li>
    </ul>
</div>